### ISSUE TITLE
0.1.0 milestone

### ISSUE THREAD

**Issue by czmirek** [czmirek/Pess#1]
- [ ] Pess.Data = Data repository library with interfaces containing IPessRepository
- [ ] Pess.Data.Xml = XML repository for projects and users.
- [ ] Simple login of users from appsettings.json
- [ ] Website layout = simple bootstrap, menu with login link
- [ ] Homepage = empty site
- [ ] Homepage for signed up user = Projects link
- [ ] List projects
- [ ] Add project (name, description)
- [ ] Edit project (name, description)
- [ ] List aggregates in project
- [ ] Add Aggregate in project (name, description)
- [ ] Edit aggregate in project (name, description)
